# ----
# Site

title: JustSketchMe
url: "https://justsketch.me"
baseurl:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: "/images/logo-blackish.png"
snippet_image: "https://imagedelivery.net/mdSbb1GKWP_xXxxsYl5evQ/33d769e5-f144-4e26-d16c-ace4e6c5dc00/optimised"
description: Character posing for artists. Give your art a headstart by creating the perfect reference image.
keywords: figure drawing reference, reference poses, posing reference, references for drawing, pose, posing, figures to draw
author:
  name:
  email: hello@justsketch.me
  twitter: justsketchme
social:
  name: JustSketchMe
  links:
    - http://justsketch.me

# -----
# Build

timezone: Etc/UTC

paginate: 100
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Reddit
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

